force-app/main/default/objects/Workflow_Audit_Log__e/Workflow_Audit_Log__e.object-meta.xml
<CustomObject>
    <description>The workflow audit log platform event is used to log errors or exceptions encountered during a workflow, providing an audit trail without interrupting the process flow.</description>
    <label>Workflow Audit Log</label>
    <pluralLabel>Workflow_Audit_Log</pluralLabel>
</CustomObject>

force-app/main/default/objects/Workflow_Audit_Log__e/fields/Audit_Text__c.field-meta.xml
<CustomField>
    <fullName>Audit_Text__c</fullName>
    <label>Audit Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Workflow_Audit_Log__e/fields/Interface_Context__c.field-meta.xml
<CustomField>
    <fullName>Interface_Context__c</fullName>
    <label>Interface Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Workflow_Audit_Log__e/fields/Primary_Object_ID__c.field-meta.xml
<CustomField>
    <fullName>Primary_Object_ID__c</fullName>
    <label>Primary Object ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Workflow_Audit_Log__e/fields/Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Process_Type__c</fullName>
    <label>Process Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Workflow_Audit_Log__e/fields/Workflow_Stage__c.field-meta.xml
<CustomField>
    <fullName>Workflow_Stage__c</fullName>
    <label>Workflow Stage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Workflow_Audit_Log__e/fields/Workflow_Type__c.field-meta.xml
<CustomField>
    <fullName>Workflow_Type__c</fullName>
    <label>Workflow Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkflowAuditEventUtility.cls
global class WorkflowAuditEventUtility{

    @InvocableMethod
    global static void createWorkFlowAuditEvent(List <WorkflowAuditInputParams> inputs){
        for(WorkflowAuditInputParams c : inputs){
            new WorkflowAuditEventUtility(c.primaryObjectId, c.workflowType, c.workflowStage, c.processType, c.auditText, c.interfaceContext);
        }
    }

    global WorkflowAuditEventUtility(String primaryObjectId, String workflowType, String workflowStage, String processType, String auditLog, String interfaceContext){

        Workflow_Audit_Log__e workflowAuditLog = new Workflow_Audit_Log__e(Primary_Object_ID__c = primaryObjectId, Workflow_Type__c = workflowType, Workflow_Stage__c = workflowStage, Process_Type__c = processType, Audit_Text__c = auditLog, Interface_Context__c = interfaceContext);

        // Call method to publish events
        Database.SaveResult result;

        try{
            result = EventBus.publish(workflowAuditLog);
        }catch(Exception e){
            System.debug('Failed to create Workflow Audit platform event.  Primary Object Id: ' + primaryObjectId + ', Audit Log: ' + auditLog + ', Workflow Type: ' + workflowType + ', Workflow Stage: ' + workflowStage + ', Process Type: ' + processType + ', Interface Context: ' + interfaceContext);
        }
    }

    @TestVisible
    global class WorkflowAuditInputParams {
        @invocableVariable(
            required = true 
            label = 'Primary Object Id'
            description = 'Primary object ID for process which originated this call'
        )
        global String primaryObjectId;

        @invocableVariable(
            required = true 
            label = 'Workflow Type'
            description = 'Workflow type which originated this call'
        )
        global String workflowType;

        @invocableVariable(
            required = true 
            label = 'Workflow Stage'
            description = 'Workflow stage which originated this call'
        )
        global String workflowStage;
        
        @invocableVariable(
            required = true 
            label = 'Process Type'
            description = 'Process type which originated this call'
        )
        global String processType;

        @invocableVariable(
            required = true 
            label = 'Audit Text'
            description = 'Audit text to be logged in Workflow Audit'
        )
        global String auditText;

        @invocableVariable(
            required = true 
            label = 'Interface Context'
            description = 'Interface context which originated this call'
        )
        global String interfaceContext;
    }
}